### ISSUE TITLE
Hebrew translations

### ISSUE THREAD

**Issue by chenraz** [cortezaproject/corteza-locale#14]
**Is your feature request related to a problem? Please describe.**
I would like to contribute adding Hebrew support

**Describe the solution you'd like**
I created a fork [repository](https://github.com/chenraz/corteza-locale.git) with Hebrew translations. currently it cover most of the corteza-serverr/auth translation, and significant part of the corteza-webapp-compose module.

**Describe alternatives you've considered**
I would like to push my fork into this repository. please let me know if this is OK and if I have to do anything other than pushing the fork

**Comment by zmija** [comment]
Hi @chenraz, thanks so much for your contribution! I've recently set up Crowdin to manage translations, so I just need to allocate some time next week to validate if everything syncs as it should and merge it to the main branch.

Fyi - we plan to add right-to-left support in the upcoming month or two. Stay tuned :)

**Comment by chenraz** [comment]
Thanks for your reply  
Let me know if you need any help from my side for the pull request.
Very happy to hear about the RTL support.   
If you need, I'll be very happy to contribute on this as well, as I already have implemented it, almost without any problem - using [postcss-rtl](https://www.npmjs.com/package/postcss-rtl)  

Here are some screenshots (it's with my customer's logo instead of Corteza's, but you can get the idea...)  

![image](https://user-images.githubusercontent.com/11751857/139589018-83a70d3e-bc18-41bf-892a-e5aa036e64a2.png)

![image](https://user-images.githubusercontent.com/11751857/139589052-f663c14e-afee-47d2-91f9-f3d709e021f7.png)

![image](https://user-images.githubusercontent.com/11751857/139589072-17cbb871-831c-437e-8371-d5ecde1582a4.png)

![image](https://user-images.githubusercontent.com/11751857/139589137-612ef315-f231-4287-8048-906c770772fb.png)

**Comment by zmija** [comment]
hello @chenraz,

How are you?

I came here to let you know we plan to allocate some time for RTL support in the upcoming two weeks, so these screenshots are a very nice surprise... :) we're very interested to see how you handled it, is there any chance you open a pull request with your implementation?

Thanks!

**Comment by chenraz** [comment]
Very happy to hear about the RTL progress.  
Of course I'll be happy to open a pull request.  
The thing is, that my version is a fork - forcing the whole system into RTL (suitable for my needs), but I guess that the pull request will need to make the RTL conditional.  
Actually, I have not only 1 fork, but a fork for each corteza-webapp-* repository.  
So i wonder - should I just open a pull request on each such repository, or should we implement it conditionally first (as i said, I am willing to contribute on that)
To be more clear, here is an example for a commit in corteza-webapp-one. You can also see it [here](https://github.com/chenraz/corteza-webapp-one/commit/c73e4356557a51f5459623093bff4831f8ae27a2) (of course, for the pull request, i will rebase only the relevant commits)

![image](https://user-images.githubusercontent.com/11751857/141279069-cd0524f3-c3ef-464f-bb60-b5abd861f1f4.png)

Please let me know how you think to proceeded, as I am fully enjoying this amazing system, and very eager to contribute

**Comment by zmija** [comment]
Hi @chenraz,

believe it or not, but this is really helpful :) it's the first time we're doing RTL, and we weren't quite sure where to start.

We can add the dir tag and the sass file directly. But I firmly believe it's more fair and appropriate you make a pull request, so you're officially listed as a contributor on the Corteza project.

So can I kindly ask you to open a PR with these UI changes, and we take care of the configuration (so it will be possible to switch between RTL and LTR from settings)? We allocated some time to tackle this in the current dev sprint (most likely Thursday and Friday).

Cheers!

**Comment by chenraz** [comment]
Great,
I'll open the pull requests soon

**Comment by zmija** [comment]
Awesome, thanks @chenraz 💪

**Comment by chenraz** [comment]
Hi @zmija,

As discussed, I had opened 3 pull requests:

https://github.com/cortezaproject/corteza-server/pull/290
https://github.com/cortezaproject/corteza-webapp-one/pull/88 
https://github.com/cortezaproject/corteza-webapp-compose/pull/341

Let me know if you need any more help from my side

**Comment by zmija** [comment]
Hi @chenraz that was fast; thank you :) 

Will you please do the same on https://github.com/cortezaproject/corteza-webapp-admin and https://github.com/cortezaproject/corteza-webapp-workflow

//cc @petergrlica: please see this, we need to make dir="rtl" configurable based on the selected language

**Comment by chenraz** [comment]
Hi @zmija 

I wouldn't mind do the same for the other 2 other repos.  

But keep in minds that the terms in those apps are mostly functions, expressions etc.  
Translating all these will take very much time. Also - it will be very dificult for the end users to search for help on those terms - they wouldn't find much if they don't search for it in English, and they wouldn't know what to search for .  

If we don't translate all those terms, we will get a mixed rtl-ltr hebrew-english screens, that would make it very hard on the end-users.

This is why, for my own use-cases, I decided to implement RTL only on the end user screens (webapp-compose, webapp-one, and the auth app)

At the very least I believe it should be configurable per app (so we can have ltr admin/workflow screens, but rtl end-user screens.

Please let me know what you think, and I'll open the additional PRs accordingly

**Comment by chenraz** [comment]
Hi @zmija 

I've just notice your note to @petergrlica .
Please note that not only the dir="rtl" should be configurable. I beleive that also the inclusion of the postcss-rtl in the build process should be conditional: https://github.com/cortezaproject/corteza-webapp-compose/pull/341/commits/98b0a38984af0d2dbb15944c37835a2d46e95b05
As well as the inclusion of the rtl.scss files

> Hi @chenraz that was fast; thank you :)
> 
> Will you please do the same on https://github.com/cortezaproject/corteza-webapp-admin and https://github.com/cortezaproject/corteza-webapp-workflow
> 
> //cc @petergrlica: please see this, we need to make dir="rtl" configurable based on the selected language

**Comment by petergrlica** [comment]
@chenraz, thanks for the help with this feature.

I closed the server PR (https://github.com/cortezaproject/corteza-server/pull/290), but for anyone wondering, the TL;DR:
RTL was added to the webapps ([compose](https://github.com/cortezaproject/corteza-webapp-compose/pull/349/files), [admin](https://github.com/cortezaproject/corteza-webapp-admin/pull/91)) and is automatically assumed via the guessed browser language with the help of i18n Vue package.

Thanks for the help

**Comment by chenraz** [comment]
Thanks for the note @petergrlica. I'm afraid the solution of  automatically assuming RTL from  browser language is very problematic - RTL languages speakers prefer in many cases to set their browser language to English from many different reasons. They should still have the ability to control the language of the app. 

I believe a better solution would be to use the language from the user's language preference on the profile settings.

**Comment by zmija** [comment]
hi @chenraz, thanks for your feedback and apologies for the potential confusion. Peter's statement was a bit misleading - for the _default_ language setting, we do indeed check the browser language, but the selected language in the profile settings in Corteza overrides it. To summarize: if you have your browser in English, the default Corteza language will be English with LTR orientation. If you switch your language to Hebrew in Corteza, orientation will switch to RTL, regardless of the browser/OS languge. I hope that makes sense!

Thanks again for your contribution.

**Comment by chenraz** [comment]
Thanks for the update - sound better - I will try to test it when I have some time
