### ISSUE TITLE
Automated translations via Google Translate using Python Script

### ISSUE THREAD

**Issue by willnaoosmith** [cortezaproject/corteza-locale#28]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It's not an actual Feature request, but a thing i think may help with translations.
Recently i made a python script to translate the Corteza-locale files from English to Portuguese.
The script uses a Library called `deep_translator` to translate the strings automatically to any language you want (If the language is supported by the library).

**How to use it**

1. First of all, install all dependencies, using `pip`:
`pip install glob deep_translator`

2. Then, on the variable Called `"FilesLocale"`, put the Path of the `corteza-locale/src` folder
3. Then, on the variable `"NewLanguage"`, you need to set the language you want to translate to (You can use `GoogleTranslator.get_supported_languages(as_dict=True)` to check all supported Languages, read more about it [Here](https://deep-translator.readthedocs.io/en/latest/usage.html#check-supported-languages)

4. Run `python translate.py` and it should create your translated files on a folder inside the FileLocale path folder.

**TroubleShooting**
You might experience some problems if the NewLanguage Folder isn't created, which you can solve by copying the `coreteza-locale/src/en/` folder into `corteza-locale/src/yourChosenLanguageAbreviationHere`

You can download the script [here](https://github.com/cortezaproject/corteza-locale/files/7927731/translate.zip). He's not perfect, but does the job!

I hope it helps someone!

**Comment by tjerman** [comment]
This seems like a neat little thing that could come in quite handy.

Would you mind moving this to our [forum](https://forum.cortezaproject.org/)? I think that would make it easier for people to find instead of having it in GH issues.

**Comment by willnaoosmith** [comment]
No problem!
I'm going to do it soon!
